SQL> CONN /AS SYSDBA
Connected.
SQL> CONN CAROL/123;
Connected.
CREATE TABLE ESTUDIANTE(NOMBRE VARCHAR2(20)
                             , NOCUENTA NUMBER(7,0));
							 
ALTER TABLE ESTUDIANTE ADD CONSTRAINT EST_NOCUENTA_PK PRIMARY KEY(NOCUENTA);

CREATE TABLE BOLETA(CALIFICACION NUMBER(2,1),
                            NOCUENTA NUMBER(7,0));
							
ALTER TABLE BOLETA ADD CONSTRAINT BOL_NOCUENTA_FK 
FOREIGN KEY (NOCUENTA)REFERENCES ESTUDIANTE(NOCUENTA);
							
INSERT INTO ESTUDIANTE VALUES('JUAN',1);
INSERT INTO ESTUDIANTE VALUES('ANA',2);

INSERT INTO BOLETA VALUES(9.8,1);

INSERT INTO BOLETA VALUES(9,1);

INSERT INTO BOLETA VALUES(9.5,1);

INSERT INTO BOLETA VALUES(9.8,2);

INSERT INTO BOLETA VALUES(9,2);

INSERT INTO BOLETA VALUES(9.5,2);

SELECT * FROM BOLETA;

DELETE FROM BOLETA WHERE NOCUENTA=1;

DELETE FROM ESTUDIANTE WHERE NOCUENTA=1;

"BORRADO EN CASCADA"

ALTER TABLE BOLETA DROP CONSTRAINT BOL_NOCUENTA_FK;

ALTER TABLE BOLETA ADD CONSTRAINT BOL_NOCUENTA_FK FOREIGN KEY 
(NOCUENTA)REFERENCES ESTUDIANTE(NOCUENTA) ON DELETE CASCADE;

SELECT * FROM BOLETA;

SELECT * FROM ESTUDIANTE;

DELETE FROM ESTUDIANTE WHERE NOCUENTA=2;

SELECT * FROM ESTUDIANTE;

DELETE FROM ESTUDIANTE;
"SE BORRAN TODOS LOS DATOS DE ESTUDIANTE Y LOS REGUSTROS DE ESTUDIANTE"

ALTER TABLE BOLETA DROP CONSTRAINT BOL_NOCUENTA_FK;

"NUEVO CONSTRAINT PARA CUANDO SE BORRE DIGA NULL"

ALTER TABLE BOLETA ADD CONSTRAINT BOL_NOCUENTA_FK FOREIGN KEY 
(NOCUENTA)REFERENCES ESTUDIANTE(NOCUENTA) ON DELETE SET NULL;

DELETE FROM ESTUDIANTE WHERE NOCUENTA=1;

ALTER TABLE BOLETA DROP CONSTRAINT BOL_NOCUENTA_FK;

ALTER TABLE BOLETA ADD CONSTRAINT BOL_NOCUENTA_FK FOREIGN KEY 
(NOCUENTA)REFERENCES ESTUDIANTE(NOCUENTA) ON DELETE CASCADE;

"PARA VER SI EXISTE UN DELETE CASCADE O SET NULL SE USA"
SELECT CONSTRAINT_NAME, DELETE_RULE FROM USER_CONSTRAINTS;

