
CONN /AS SYSDBA

SELECT INSTR('PRECIO DEL ARTICULO','E',1,2)FROM DUAL;

SQL> SELECT LOWER ('ANA') FROM DUAL;

LOW
---
ana

SQL> SELECT UPPER('ana')FROM DUAL;

UPP
---
ANA

INSERT INTO ESTUDIANTE VALUES('JUAN',3);
INSERT INTO ESTUDIANTE VALUES('PEDRO',1);
INSERT INTO ESTUDIANTE VALUES('LUIS',4);
INSERT INTO ESTUDIANTE VALUES('ANDRES',5);

SELECT UPPER('Manuel')AS NOMBRE FROM ESTUDIANTE;

SELECT INITCAP (NOMBRE) AS NOMBRE 
FROM ESTUDIANTE;

SELECT CONCAT(NOMBRE,NOCUENTA)
FROM ESTUDIANTE;

SELECT LPAD (NOMBRE,10,'0')
FROM ESTUDIANTE;

SELECT TO CHAR (SYSDATE,YYYY) FROM DUAL;

SELECT SYSDATE FROM DUAL;

SELECT ROUND(13.1416)FROM DUAL;