CREATE TABLE DEPARTAMENTO(DEPT CHAR(4)CONSTRAINT DEPT_NN NOT NULL CONSTRAINT DEPT_PK PRIMARY KEY,
                          EDIF CHAR(2)CONSTRAINT EDIF_NN NOT NULL,
						  DESPACHO NUMBER(2,0) CONSTRAINT DESPACHO_NN NOT NULL,
						  CHFNO CHAR(3));
						  
CREATE TABLE CURSO(NO CHAR(3) CONSTRAINT NO_NN NOT NULL,
                   NOMBRE VARCHAR2(25) CONSTRAINT NOMBRE_NN NOT NULL,
				   DESCP CHAR(25) CONSTRAINT DESCP_NN NOT NULL,
				   RED NUMBER(2,0)CONSTRAINT RED_NN NOT NULL,
				   TARIFA NUMBER(5,2) CONSTRAINT TARIFA_NN NOT NULL,
				   DEPT VARCHAR(4)CONSTRAINT DEPT_NN NOT NULL,
				   CONSTRAINT NO_PK PRIMARY KEY(NO),
				   CONSTRAINT DEPT_FK FOREIGN KEY (DEPT) REFERENCES DEPARTAMENTO(DEPT));
				   
CREATE TABLE CLAUSTRO(NO CHAR(3)CONSTRAINT NO_NN NOT NULL,
                      NOMBREC CHAR(15)CONSTRAINT NOMBREC_NN NOT NULL,
					  DOMI CHAR(20)CONSTRAINT DOMI_NN NOT NULL,
					  FCANTI DATE CONSTRAINT FCANTI_NN NOT NULL,
					  NUMDEP NUMBER(2,0),
					  SUELDO NUMBER(5,2)CONSTRAINT SUELDO_NN NOT NULL,
					  DEPT CHAR(4)CONSTRAINT DEPT_NN NOT NULL);
					  
ALTER TABLE CLAUSTRO ADD CONSTRAINT NO_PK PRIMARY KEY(NO);
ALTER TABLE CLAUSTRO ADD CONSTRAINT NO_PK PRIMARY KEY(NO);
ALTER TABLE CLAUSTRO ADD CONSTRAINT DEPT_FK FOREIGN KEY (DEPT) REFERENCES DEPARTAMENTO(DEPT);

CREATE TABLE CLASE (NO CHAR(3)CONSTRAINT NO_NN NOT NULL CONSTRAINT NO_FK FOREIGN KEY (NO) REFERENCES CURSO(NO)
                    SEC VARCHAR(2)CONSTRAINT SEC_NN NOT NULL CONSTRAINT SEC_PK PRIMARY KEY,
					INSTRFNO CHAR(2)CONSTRAINT INSTRFNO_NN NOT NULL,
					DIA CHAR(2)CONSTRAINT DIA_NN NOT NULL,
					HORA CHAR(14)CONSTRAINT HORA_NN NOT NULL,
					EDIF CHAR(2)CONSTRAINT EDIF_NN NOT NULL,
					DESPACHO NUMBER(2,0)CONSTRAINT DESPACHO_NN NOT NULL);
					
CREATE TABLE ESTUDIANTE(NO CHAR(3)CONSTRAINT NO_NN NOT NULL,
                        NOMBRE CHAR(30)CONSTRAINT NOMBRE_NN NOT NULL,
						DOMI CHAR(15)CONSTRAINT DOMI_NN NOT NULL,
						TLFNO CHAR(12)CONSTRAINT TLFNO_NN NOT NULL,
						FNACIM CHAR(6)CONSTRAINT FNACIM_ NN NOT NULL,
						IQ NUMBER(3,0)CONSTRAINT IQ_NN NOT NULL,
						ADVFNO CHAR(3)CONSTRAINT ADVFNO_NN NOT NULL,
						ESP CHAR(4)CONSTRAINT ESP_NN NOT NULL,
						CONSTRAINT NO_PK PRIMARY KEY(NO)
						CONSTRAINT ESP_FK FOREIGN KEY (ESP) REFERENCES DEPARTAMENTO(DEPT)
						);
						
CREATE TABLE MATRICULA(NO char(3)CONSTRAINT MATRICULA_NN NOT NULL,
                       SEC CHAR(2)CONSTRAINT SEC_NN NOT NULL,
					   FECHAMAT DATE CONSTRAINT FECHAMAT_NN NOT NULL,
					   HORAMAT CHAR(10)CONSTRAINT HORAMAT_NN NOT NULL);
					
ALTER TABLE MATRICULA ADD CONSTRAINT NO_FK FOREIGN KEY (NO) REFERENCES ESTUDIANTE(NO);

CREATE TABLE PERSONAL(NOMBRE CHAR(15)CONSTRAINT NOMBRE_NN NOT NULL CONSTRAINT NOMBRE_PK PRIMARY KEY,
                      CARGO CHAR(10),CONSTRAINT CARGO_NN NOT NULL,
					  SUELDO NUMBER(5,0)CONSTRAINT SUELDO_NN NOT NULL,
					  DEPT CHAR(4));
