SELECT OWNER, TABLE_NAME FROM ALL_TABLES WHERE OWNER='ESCUELA';

SELECT TABLE_NAME FROM USER_TABLES;



CREATE TABLE ALUMNO (NOMBRE VARCHAR2(30)NOT NULL,
                     SEXO CHAR(1) CHECK(SEXO='M' OR SEXO='F'),
					 NOCUENTA NUMBER(7,0)PRIMARY KEY,
					 PROMEDIO NUMBER(2,1) NOT NULL CHECK(PROMEDIO>=0 AND PROMEDIO<=10),
					 FECHAINGRESO DATE NOT NULL,
					 CURP CHAR(16) NOT NULL UNIQUE);
					 
		CREATE TABLE CALIFICACIONES (NOCUENTA NUMBER(7,0),
		                             MATERIA VARCHAR2(30)UNIQUE,
									 FOREIGN KEY (NOCUENTA) REFERENCES ALUMNO(NOCUENTA)
									 );
								
DESC ALUMNO;
DESC CALIFIC

"A NIVEL COLUMNA"

CREATE TABLE ALUMNO (NOMBRE VARCHAR2(30)CONSTRAINT NOMBRE_NN NOT NULL,
                     SEXO CHAR(1)CONSTRAINT SEXO_CK CHECK(SEXO='M' OR SEXO='F'),
					 NOCUENTA NUMBER(7,0)CONSTRAINT NOCUENTA_PK PRIMARY KEY,
					 PROMEDIO NUMBER(2,1)CONSTRAINT PROMEDIO_NN NOT NULL CONSTRAINT PROMEDIO_CK CHECK(PROMEDIO>=0 AND PROMEDIO<=10),
					 FECHAINGRESO DATE CONSTRAINT FECHAINGRESO_NN NOT NULL,
					 CURP CHAR(16)CONSTRAINT CURP_NN NOT NULL CONSTRAINT CURP_UQ UNIQUE);
					 
CREATE TABLE CALIFICACIONES (NOCUENTA NUMBER(7,0),
		                     MATERIA VARCHAR2(30)CONSTRAINT MATERIA_NN UNIQUE,
						      CONSTRAINT NOCUENTA_FK FOREIGN KEY (NOCUENTA) REFERENCES ALUMNO(NOCUENTA));
							  
							  
							  
"A NIVEL TABLA"
CREATE TABLE ALUMNO (NOMBRE VARCHAR2(30)CONSTRAINT NOMBRE_NN NOT NULL,
                     SEXO CHAR(1),
					 NOCUENTA NUMBER(7,0),
					 PROMEDIO NUMBER(2,1) CONSTRAINT PROMEDIO_NN NOT NULL,
					 FECHAINGRESO DATE CONSTRAINT FECHAINGRESO_NN NOT NULL,
					 CURP CHAR(16)CONSTRAINT CURP_NN NOT NULL,
					 CONSTRAINT SEXO_CK CHECK(SEXO='M' OR SEXO='F'),
					 CONSTRAINT NOCUENTA_PK PRIMARY KEY(NOCUENTA),
					 CONSTRAINT PROMEDIO_CK CHECK(PROMEDIO>=0 AND PROMEDIO<=10),
					 CONSTRAINT CURP_UQ UNIQUE(CURP)
					 );

CREATE TABLE CALIFICACIONES (NOCUENTA NUMBER(7,0),
		                     MATERIA VARCHAR2(30)CONSTRAINT MATERIA_NN NOT NULL,
						     CONSTRAINT NOCUENTA_FK FOREIGN KEY (NOCUENTA) REFERENCES ALUMNO(NOCUENTA));
							 
"CON ALTER TABLE "
CREATE TABLE ALUMNO (NOMBRE VARCHAR2(30)CONSTRAINT NOMBRE_NN NOT NULL,
                     SEXO CHAR(1),
					 NOCUENTA NUMBER(7,0),
					 PROMEDIO NUMBER(2,1) CONSTRAINT PROMEDIO_NN NOT NULL,
					 FECHAINGRESO DATE CONSTRAINT FECHAINGRESO_NN NOT NULL,
					 CURP CHAR(16)CONSTRAINT CURP_NN NOT NULL);
					 
ALTER TABLE ALUMNO ADD CONSTRAINT SEXO_CK CHECK(SEXO='M' OR SEXO='F');
ALTER TABLE ALUMNO ADD CONSTRAINT NOCUENTA_PK PRIMARY KEY(NOCUENTA);
ALTER TABLE ALUMNO ADD CONSTRAINT PROMEDIO_CK CHECK(PROMEDIO>=0 AND PROMEDIO<=10);
ALTER TABLE ALUMNO ADD CONSTRAINT CURP_UQ UNIQUE(CURP);

CREATE TABLE CALIFICACIONES (NOCUENTA NUMBER(7,0),
		                     MATERIA VARCHAR2(30));
							 
ALTER TABLE CALIFICACIONES ADD CONSTRAINT NOCUENTA_FK FOREIGN KEY (NOCUENTA) REFERENCES ALUMNO(NOCUENTA);