1-
SELECT MIN(E.SALARY),
       D.DEPARTMENT_NAME
FROM EMPLOYEES E, DEPARTMENTS D
HAVING MAX(E.SALARY) < 5000
GROUP BY D.DEPARTMENT_ID;

2-
SELECT COUNTRY_NAME
       REGION_NAME
FROM COUNTRIES
NATURAL JOIN REGIONS;

3-
SELECT E.DEPARTMENT_ID,
       JOB_ID,
	   E.EMPLOYEE_ID,
	   E.FIRST_NAME
FROM EMPLOYEES E JOIN JOB_HISTORY
USING(JOB_ID);

4-
SELECT E.FIRST_NAME,
       D.DEPARTMENT_NAME
FROM EMPLOYEES E
   JOIN DEPARTMENTS D
ON E.EMPLOYEE_ID = D.MANAGER_ID;

5-
SELECT ISNULL(E.FIRST_NAME),
       D.DEPARTMENT_NAME
FROM EMPLOYEES E
LEFT JOIN DEPARTMENTS D
ON E.EMPLOYEE_ID=D.MANAGER_ID;

SELECT E.FIRST_NAME,
       D.DEPARTMENT_NAME
FROM EMPLOYEES E
LEFT JOIN DEPARTMENTS D
ON E.EMPLOYEE_ID=D.MANAGER_ID;

6-
SELECT ISNULL(E.FIRST_NAME),
       D.DEPARTMENT_NAME
FROM EMPLOYEES E
RIGHT JOIN DEPARTMENTS D
ON E.EMPLOYEE_ID=D.MANAGER_ID;

SELECT E.FIRST_NAME,
       D.DEPARTMENT_NAME
FROM EMPLOYEES E
RIGHT JOIN DEPARTMENTS D
ON E.EMPLOYEE_ID=D.MANAGER_ID;

7-
SELECT ISNULL(E.FIRST_NAME),
       D.DEPARTMENT_NAME
FROM EMPLOYEES E
FULL JOIN DEPARTMENTS D
ON E.EMPLOYEE_ID=D.MANAGER_ID;

SELECT E.FIRST_NAME,
       D.DEPARTMENT_NAME
FROM EMPLOYEES E
FULL JOIN DEPARTMENTS D
ON E.EMPLOYEE_ID=D.MANAGER_ID;

8-
SELECT ISNULL(E.FIRST_NAME),
       D.DEPARTMENT_NAME
FROM EMPLOYEES E
INNER JOIN DEPARTMENTS D
ON E.EMPLOYEE_ID=D.MANAGER_ID;

SELECT E.FIRST_NAME,
       D.DEPARTMENT_NAME
FROM EMPLOYEES E
INNER JOIN DEPARTMENTS D
ON E.EMPLOYEE_ID=D.MANAGER_ID;